// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeZeKV3FMwhCqd9dQviBkSnAkn98YS0Hg',
    appId: '1:939373166356:web:2b7a20892a98d026544c01',
    messagingSenderId: '939373166356',
    projectId: 'regenera-f183f',
    authDomain: 'regenera-f183f.firebaseapp.com',
    storageBucket: 'regenera-f183f.appspot.com',
    measurementId: 'G-YXMXZECW8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ejR7p-15SB9EnAFjnzBEHZYLKDTdf_4',
    appId: '1:939373166356:android:b8fd3c09b63006c6544c01',
    messagingSenderId: '939373166356',
    projectId: 'regenera-f183f',
    storageBucket: 'regenera-f183f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj4EUa_a4bmK_kXY79vLOI6uzwW22Pviw',
    appId: '1:939373166356:ios:31cc50b9839ee31c544c01',
    messagingSenderId: '939373166356',
    projectId: 'regenera-f183f',
    storageBucket: 'regenera-f183f.appspot.com',
    iosBundleId: 'com.mondi.regenera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj4EUa_a4bmK_kXY79vLOI6uzwW22Pviw',
    appId: '1:939373166356:ios:b703311bc23e2fd5544c01',
    messagingSenderId: '939373166356',
    projectId: 'regenera-f183f',
    storageBucket: 'regenera-f183f.appspot.com',
    iosBundleId: 'com.mondi.regenera.RunnerTests',
  );
}
